### ISSUE TITLE
Add testing utility to mock the crud client

### ISSUE THREAD

**Issue by davidebianchi** [mia-platform/go-crud-service-client#25]

**Comment by malta895** [comment]
Hi, could we implement an interface `CRUDClient` and then make our library return an instance of this interface instead of a struct in [this function](https://github.com/mia-platform/go-crud-service-client/blob/12a28962f2d68c6ec054e0e5e44da1104579edb0/client.go#L35)? 

Then users that want to test the library could just reimplement the interface with mock crudClient structs in their tests, lifting them from the responsibility of mocking http requests.

What do you think?

**Comment by malta895** [comment]
A similar approach is described in [Effective Go](https://go.dev/doc/effective_go#generality)

**Comment by fredmaggiowski** [comment]
I agree with you @malta895 this seems like the best strategy

**Comment by davidebianchi** [comment]
Yes, the interface the intended strategy. 
Since there are a lot of methods, the testing utility supposed here is a ready to use mock which enable the user to do some assertion. This could simplify the devx, since in Mia we use this lib in different services and recreate the utility in all of them is quite useless. What do you think about?

**Comment by malta895** [comment]
Yes this sounds good to me.

We could create another struct, say `crudTest`, that implements the same interface. Then we export a function `NewCrudTest` that returns an instance of this struct, but with the type of the interface, taking as argument something like  a `TestOptions` struct, that will be initialized by the user with mocked results/implementations of the methods.

The library will only export the interface, the two `New...` functions, and the `TestOptions` struct.

What do you think about it?

**Comment by davidebianchi** [comment]
Yes, something similar. I'd prefers to have a specific package, something like crudclienttest, so that we could use it with: crudclienttest.NewClient, or something similar

**Comment by fredmaggiowski** [comment]
I agree with having a testing package

**Comment by fredmaggiowski** [comment]
I've implemented the interace in #34 

I'll provide a mock in a future PR

**Comment by fredmaggiowski** [comment]
With #35 this can be resolved
